### ISSUE TITLE
Type erasure

### ISSUE THREAD

**Issue by yonaskolb** [StevenLambion/SwiftDux#10]
Hi, this seems a fantastic and well fleshed out library!

One concern I have is that `StateConnectionViewGuard` is type erasing the view hierarchy with `AnyView`, which is far as I understand removes the optimizations SwiftUI applies when rendering.
As this is applied on any use of `connect()` it basically affects the whole tree when used.

**Comment by StevenLambion** [comment]
Thanks for pointing that out. That definitely needs to be changed.

**Comment by StevenLambion** [comment]
This should be fixed in v0.11.1.
