### ISSUE TITLE
dispatch from action handler

### ISSUE THREAD

**Issue by hoopes** [StevenLambion/SwiftDux#37]
Hi,

I had asked a question in https://github.com/StevenLambion/SwiftDux/issues/28 where I was trying to find the proper incantation to dispatch another action from an action handler, but was looking for some clarification.

Cribbing from the README a bit:

```final class TodosReducer: Reducer {

  func reduce(state: OrderedState<TodoItem>, action: TodoAction) -> OrderedState<TodoItem> {
    var state = state
    switch action {
    case .addTodo(let text):
      let id = UUID().uuidString
      state.append(TodoItemState(id: id, text: text))
      ////// DISPATCH ACTION HERE ///////
    }
    return state
  }
}
```

It doesn't _appear_ that I can import the `dispatch` function like it's used in the views. I might not be using it right, though.

Is there an obvious way to do this that I'm missing?

A particular use-case I'm running into now is there are some number of actions that set individual flags, and a more general action that reads all of those flags for something else. (I can elaborate on that, if it doesn't make sense, or would help in any way.)

Much obliged!  FWIW, I'm currently using the `swift-5.2` branch.

**Comment by StevenLambion** [comment]
The reducer's job is to consume a single action that mutates the state. In this particular case, I'd look at implementing an ActionPlan that dispatches two or more actions.

I like to add them as static functions to the action's enum:
 
```swift
extension TodoAction {
  static func addTodoAndUpdateCount(_ text: String) -> ActionPlan<AppState> {
    ActionPlan { store in
       store.send(TodoAction.addTodo(text)
       store.send(TodoListAction.updateCount)
    }
  }
}

....

// Dispatch it like any other action:
dispatch(TodoAction.addTodoAndUpdateCount(self.newText)
```

**Comment by hoopes** [comment]
Does that guarantee to run them in that order? If so, what should I use the `then` for?

```
static var initialize: ActionPlan<AppState> {
        ActionPlan { store in
            store.send(SubAction.beginInit)
            store.send(GlobalAction.updateInitialization)
        }
        .then(ActionPlan { store in
            store.send(SubAction.completeInit)
            store.send(GlobalAction.updateInitialization)
        })
    }
```

Thanks!

**Comment by StevenLambion** [comment]
If the sent actions are just regular actions, they are guaranteed to be synchronously sent one after the next. The library does make the assumption that all actions are sent from the same thread. This is typically the main thread.

When sending an action plan, there's the possibility that it may perform an asynchronous job. In this case, the "then" methods is required to guarantee the order of execution.
