### ISSUE TITLE
Question: Async actions (async thunk-like)

### ISSUE THREAD

**Issue by gioele-santi** [StevenLambion/SwiftDux#56]
I recently discovered this project and I find it really promising, but checking readme file and example project I could not figure out how to perform an async action like async thunks in redux.

For example if I need to perform a login with a remote service I would need an action with 2 parameters (id, pw) that should trigger a background request and set a loading= true and then upon completion report success or fail using 2 other actions. 

I thought Action Plans could be the right way but I am not sure about passing 2 parameters to an action plan.

Maybe I am missing something?
Thank you.

**Comment by kamilpowalowski** [comment]
Hi, I looked at my code and found an example of Action plan that takes two arguments:

```swift
static func purchaseProduct(
        paymentService: PaymentService,
        product: Product
    ) -> ActionPlan<AppState> {
        ActionPlan<AppState> { store -> AnyPublisher<Action, Never> in
            paymentService.purchaseProduct(product)
                .catch { _ in Just<Pro?>(store.state.proState.pro) }
                .map { ProAction.setProStatus($0) }
                .eraseToAnyPublisher()
        }
    }
```
You can use the `.map` function to dispatch two different actions as you described.

**Comment by gioele-santi** [comment]
Thank you very much! I will try it tomorrow.

**Comment by gioele-santi** [comment]
it works perfectly. I think this example could be useful in the readme and that you could close the issue.
