### ISSUE TITLE
ActionPlan that returns optional publisher?

### ISSUE THREAD

**Issue by aputinski** [StevenLambion/SwiftDux#58]
In the example code for `ActionPlan`, I see it conditionally returning `nil` at the top and then returning an action publisher at the bottom, but I don't see any initializers that support that return type? Is that a typo in the example or am I not understanding correctly?

https://github.com/StevenLambion/SwiftDux/blob/master/Sources/SwiftDux/Action/ActionPlan.swift#L11

**Comment by kamilpowalowski** [comment]
I believe this is a mistake in the documentation. In that example instead of `return nil` it should be `return Empty().eraseToAnyPublisher()`

**Comment by StevenLambion** [comment]
Thanks for spotting this. I’m going to do a review of the documentation to make sure it’s as accurate as possible.

**Comment by aputinski** [comment]
Thanks!
